"""learning contracts

Revision ID: 20261009_0022
Revises: 20261009_0021
Create Date: 2026-10-09 13:45:08.009344
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20261009_0022"
down_revision: str | Sequence[str] | None = "20261009_0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("skill_versions", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_skill_versions_id_skill", ["id", "skill_id"])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_kind", sa.String(length=16), nullable=False),
        sa.Column("parent_request_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("origin_run_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("source_key", sa.String(length=160), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=False),
        sa.Column("request_body_hash", sa.String(length=71), nullable=False),
        sa.Column("feedback_revision", sa.Integer(), nullable=False),
        sa.Column("target_skill_id", sa.Uuid(), nullable=True),
        sa.Column("base_version_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("policy_snapshot", sa.JSON(), nullable=False),
        sa.Column("policy_hash", sa.String(length=71), nullable=False),
        sa.Column("frozen_inputs", sa.JSON(), nullable=False),
        sa.Column("candidate_version_id", sa.Uuid(), nullable=True),
        sa.Column("validation_experiment_id", sa.Uuid(), nullable=True),
        sa.Column("validation_report", sa.JSON(), nullable=True),
        sa.Column("validation_report_hash", sa.String(length=71), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            (
                "(request_kind = 'propose' AND source_key LIKE 'propose:v1:%') OR "
                "(request_kind = 'validate' AND source_key LIKE 'validate:v1:%')"
            ),
            name=op.f("ck_learning_requests_identity_namespace"),
        ),
        sa.ForeignKeyConstraint(
            ["base_version_id"],
            ["skill_versions.id"],
            name=op.f("fk_learning_requests_base_version_id_skill_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_version_id"],
            ["skill_versions.id"],
            name=op.f("fk_learning_requests_candidate_version_id_skill_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_run_id"], ["runs.id"], name=op.f("fk_learning_requests_origin_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["parent_request_id"],
            ["learning_requests.id"],
            name=op.f("fk_learning_requests_parent_request_id_learning_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_learning_requests_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["target_skill_id"],
            ["skills.id"],
            name=op.f("fk_learning_requests_target_skill_id_skills"),
        ),
        sa.ForeignKeyConstraint(
            ["validation_experiment_id"],
            ["eval_experiments.id"],
            name=op.f("fk_learning_requests_validation_experiment_id_eval_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_learning_requests_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_requests")),
        sa.UniqueConstraint(
            "workspace_id", "client_request_id", name="uq_learning_requests_client_request"
        ),
        sa.UniqueConstraint("workspace_id", "source_key", name="uq_learning_requests_source_key"),
    )
    with op.batch_alter_table("learning_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_learning_requests_scope_status",
            ["workspace_id", "status", "created_at"],
            unique=False,
        )

    op.create_table(
        "learning_request_aliases",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("client_request_id", sa.String(128), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("request_body_hash", sa.String(71), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"]),
        sa.ForeignKeyConstraint(["request_id"], ["learning_requests.id"]),
        sa.PrimaryKeyConstraint("workspace_id", "client_request_id"),
    )
    op.create_table(
        "learning_policies",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("daily_limit_micros", sa.Integer(), nullable=True),
        sa.Column("request_limit_micros", sa.Integer(), nullable=True),
        sa.Column("daily_candidate_limit", sa.Integer(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("max_source_risk", sa.String(length=8), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mode IN ('off','manual','suggest')", name=op.f("ck_learning_policies_mode_valid")
        ),
        sa.CheckConstraint(
            "daily_limit_micros IS NULL OR daily_limit_micros >= 0",
            name=op.f("ck_learning_policies_daily_budget_valid"),
        ),
        sa.CheckConstraint(
            "request_limit_micros IS NULL OR request_limit_micros >= 0",
            name=op.f("ck_learning_policies_request_budget_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_learning_policies_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_learning_policies")),
    )
    op.create_table(
        "learning_spend_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("call_key", sa.String(length=160), nullable=False),
        sa.Column("budget_day", sa.String(length=10), nullable=False),
        sa.Column("reserved_micros", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("actual_micros", sa.Integer(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('reserved','settled','unknown','released')",
            name=op.f("ck_learning_spend_reservations_status_valid"),
        ),
        sa.CheckConstraint(
            "reserved_micros >= 0", name=op.f("ck_learning_spend_reservations_reserved_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["learning_requests.id"],
            name=op.f("fk_learning_spend_reservations_request_id_learning_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_learning_spend_reservations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_spend_reservations")),
        sa.UniqueConstraint("call_key", name=op.f("uq_learning_spend_reservations_call_key")),
    )
    with op.batch_alter_table("learning_spend_reservations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_learning_spend_day", ["workspace_id", "budget_day", "status"], unique=False
        )

    op.create_table(
        "run_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("learning_revision", sa.Integer(), nullable=False),
        sa.Column("learning_payload_hash", sa.String(length=71), nullable=False),
        sa.Column("request_body_hash", sa.String(length=71), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("correction", sa.Text(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intent IN ('method','fact','unsure','mixed')",
            name=op.f("ck_run_feedback_intent_valid"),
        ),
        sa.CheckConstraint(
            "verdict IN ('helpful','needs_fix','incorrect')",
            name=op.f("ck_run_feedback_verdict_valid"),
        ),
        sa.CheckConstraint(
            "revision >= 1 AND learning_revision >= 1",
            name=op.f("ck_run_feedback_revisions_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_feedback_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["run_feedback.id"],
            name=op.f("fk_run_feedback_supersedes_id_run_feedback"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_feedback")),
        sa.UniqueConstraint("run_id", "client_request_id", name="uq_run_feedback_client_request"),
        sa.UniqueConstraint("run_id", "revision", name="uq_run_feedback_revision"),
    )
    with op.batch_alter_table("run_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_feedback_run_id"), ["run_id"], unique=False)

    op.create_table(
        "learning_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=True),
        sa.Column("source_revision", sa.String(length=71), nullable=False),
        sa.Column("source_role", sa.String(length=32), nullable=False),
        sa.Column("parent_skill_versions", sa.JSON(), nullable=False),
        sa.Column("evidence_manifest", sa.JSON(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revocation_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_learning_sources_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["run_feedback.id"],
            name=op.f("fk_learning_sources_feedback_id_run_feedback"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_learning_sources_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_sources")),
        sa.UniqueConstraint("run_id", "source_revision", name=op.f("uq_learning_sources_run_id")),
    )
    with op.batch_alter_table("learning_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_learning_sources_run_id"), ["run_id"], unique=False)

    with op.batch_alter_table("maintenance_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), server_default="0", nullable=False))
        batch_op.add_column(
            sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.add_column(sa.Column("learning_request_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("result_schema_version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_maintenance_jobs_learning_request_id_learning_requests"),
            "learning_requests",
            ["learning_request_id"],
            ["id"],
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("next_event_sequence", sa.Integer(), server_default="1", nullable=False)
        )

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("data_role", sa.String(length=32), server_default="legacy", nullable=False)
        )
        batch_op.add_column(
            sa.Column("next_feedback_revision", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("next_context_revision", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.create_check_constraint(
            "data_role_valid",
            "data_role IN ('personal','dev','train','holdout','runtime_eval','legacy')",
        )

    with op.batch_alter_table("skill_sources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source_kind", sa.String(length=32), server_default="train_eval", nullable=False
            )
        )
        batch_op.add_column(sa.Column("learning_source_id", sa.Uuid(), nullable=True))
        batch_op.alter_column("source_eval_run_id", existing_type=sa.CHAR(length=32), nullable=True)
        batch_op.create_foreign_key(
            batch_op.f("fk_skill_sources_learning_source_id_learning_sources"),
            "learning_sources",
            ["learning_source_id"],
            ["id"],
        )
        batch_op.create_check_constraint(
            "source_kind_exclusive",
            (
                "(source_kind='train_eval' AND source_eval_run_id IS NOT NULL AND "
                "learning_source_id IS NULL) OR (source_kind='personal' AND "
                "source_eval_run_id IS NULL AND learning_source_id IS NOT NULL)"
            ),
        )

    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "workspace_id",
                sa.Uuid(),
                server_default="00000000000000000000000000000001",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("project_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("superseded_by_skill_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("next_version_number", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("next_event_sequence", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.drop_constraint(batch_op.f("uq_skills_slug"), type_="unique")
        batch_op.create_unique_constraint("uq_skills_workspace_slug", ["workspace_id", "slug"])
        batch_op.create_foreign_key(
            batch_op.f("fk_skills_superseded_by_skill_id_skills"),
            "skills",
            ["superseded_by_skill_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_skills_workspace_id_workspaces"), "workspaces", ["workspace_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_skills_project_id_projects"), "projects", ["project_id"], ["id"]
        )

    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.alter_column("workspace_id", server_default=None)

    with op.batch_alter_table("spend_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("purpose", sa.String(length=32), server_default="legacy", nullable=False)
        )
        batch_op.add_column(sa.Column("learning_request_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("reservation_id", sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_spend_records_reservation_id"), ["reservation_id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_spend_records_reservation_id_learning_spend_reservations"),
            "learning_spend_reservations",
            ["reservation_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_spend_records_learning_request_id_learning_requests"),
            "learning_requests",
            ["learning_request_id"],
            ["id"],
        )

    op.execute(
        "UPDATE projects SET next_event_sequence = COALESCE((SELECT "
        "MAX(sequence)+1 FROM project_events WHERE project_id=projects.id), 1)"
    )
    op.execute(
        "UPDATE skills SET next_event_sequence = COALESCE((SELECT "
        "MAX(sequence)+1 FROM skill_events WHERE skill_id=skills.id), 1)"
    )
    op.execute(
        "UPDATE skills SET next_version_number = COALESCE((SELECT "
        "MAX(version)+1 FROM skill_versions WHERE skill_id=skills.id), 1)"
    )
    op.execute(
        "UPDATE runs SET next_context_revision = COALESCE((SELECT "
        "MAX(revision)+1 FROM context_revisions WHERE run_id=runs.id), 1)"
    )
    op.execute(
        "UPDATE runs SET data_role = (SELECT eval_cases.split FROM eval_cases "
        "JOIN eval_runs ON eval_cases.id=eval_runs.eval_case_id WHERE "
        "eval_runs.run_id=runs.id) WHERE EXISTS (SELECT 1 FROM eval_runs WHERE "
        "eval_runs.run_id=runs.id)"
    )
    op.execute(
        "UPDATE runs SET data_role='runtime_eval' WHERE EXISTS (SELECT 1 FROM "
        "runtime_eval_runs WHERE runtime_eval_runs.run_id=runs.id)"
    )
    _role_trigger(True)


def downgrade() -> None:
    # 有新语义数据时不能静默丢弃或降级为旧版本可读取的训练来源。
    bind = op.get_bind()
    for table in (
        "learning_requests",
        "run_feedback",
        "learning_sources",
        "learning_spend_reservations",
    ):
        if bind.scalar(sa.text(f"SELECT COUNT(*) FROM {table}")):
            raise RuntimeError(
                "learning data exists; downgrade requires an explicit export and removal"
            )
    _role_trigger(False)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spend_records", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_spend_records_learning_request_id_learning_requests"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_spend_records_reservation_id_learning_spend_reservations"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(batch_op.f("uq_spend_records_reservation_id"), type_="unique")
        batch_op.drop_column("reservation_id")
        batch_op.drop_column("learning_request_id")
        batch_op.drop_column("purpose")

    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_skills_project_id_projects"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_skills_workspace_id_workspaces"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_skills_superseded_by_skill_id_skills"), type_="foreignkey"
        )
        batch_op.drop_constraint("uq_skills_workspace_slug", type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_skills_slug"), ["slug"])
        batch_op.drop_column("next_event_sequence")
        batch_op.drop_column("next_version_number")
        batch_op.drop_column("superseded_by_skill_id")
        batch_op.drop_column("project_id")
        batch_op.drop_column("workspace_id")

    with op.batch_alter_table("skill_sources", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("ck_skill_sources_source_kind_exclusive"), type_="check")
        batch_op.drop_constraint(
            batch_op.f("fk_skill_sources_learning_source_id_learning_sources"), type_="foreignkey"
        )
        batch_op.alter_column(
            "source_eval_run_id", existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.drop_column("learning_source_id")
        batch_op.drop_column("source_kind")

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("next_context_revision")
        batch_op.drop_column("next_feedback_revision")
        batch_op.drop_constraint(op.f("ck_runs_data_role_valid"), type_="check")
        batch_op.drop_column("data_role")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("next_event_sequence")

    with op.batch_alter_table("maintenance_jobs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_maintenance_jobs_learning_request_id_learning_requests"),
            type_="foreignkey",
        )
        batch_op.drop_column("result_schema_version")
        batch_op.drop_column("learning_request_id")
        batch_op.drop_column("cancel_requested")
        batch_op.drop_column("priority")

    with op.batch_alter_table("learning_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_sources_run_id"))

    op.drop_table("learning_sources")
    with op.batch_alter_table("run_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_feedback_run_id"))

    op.drop_table("run_feedback")

    with op.batch_alter_table("skill_versions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_skill_versions_id_skill", type_="unique")

    with op.batch_alter_table("learning_spend_reservations", schema=None) as batch_op:
        batch_op.drop_index("ix_learning_spend_day")

    op.drop_table("learning_spend_reservations")
    op.drop_table("learning_policies")
    with op.batch_alter_table("learning_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_learning_requests_scope_status")

    op.drop_table("learning_request_aliases")
    op.drop_table("learning_requests")
    # ### end Alembic commands ###


def _role_trigger(create):
    if op.get_bind().dialect.name == "sqlite":
        if create:
            op.execute(
                "CREATE TRIGGER runs_data_role_immutable BEFORE UPDATE OF data_role ON "
                "runs WHEN NEW.data_role != OLD.data_role BEGIN SELECT RAISE(ABORT, "
                "'run data_role is immutable'); END"
            )
        else:
            op.execute("DROP TRIGGER IF EXISTS runs_data_role_immutable")
    elif create:
        op.execute(
            "CREATE FUNCTION protect_run_data_role() RETURNS trigger LANGUAGE "
            "plpgsql AS $$ BEGIN IF NEW.data_role IS DISTINCT FROM OLD.data_role "
            "THEN RAISE EXCEPTION 'run data_role is immutable'; END IF; RETURN "
            "NEW; END $$"
        )
        op.execute(
            "CREATE TRIGGER runs_data_role_immutable BEFORE UPDATE OF data_role ON "
            "runs FOR EACH ROW EXECUTE FUNCTION protect_run_data_role()"
        )
    else:
        op.execute("DROP TRIGGER IF EXISTS runs_data_role_immutable ON runs")
        op.execute("DROP FUNCTION IF EXISTS protect_run_data_role()")
