"""embedding_and_frozen_retrieval

Revision ID: 20260920_0007
Revises: 20260919_0006
Create Date: 2026-09-20 14:16:57.650941
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from evoagent.retrieval.vector import PGVector

revision: str = "20260920_0007"
down_revision: str | Sequence[str] | None = "20260919_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "maintenance_jobs", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("preprocessing", sa.String(length=64), nullable=False),
        sa.Column("active_generation", sa.Integer(), nullable=False),
        sa.Column("next_generation", sa.Integer(), nullable=False),
        sa.CheckConstraint("dimension = 1536", name=op.f("ck_embedding_profiles_fixed_dimension")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_profiles")),
        sa.UniqueConstraint("model", name=op.f("uq_embedding_profiles_model")),
    )
    op.create_table(
        "index_generations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["embedding_profiles.id"],
            name=op.f("fk_index_generations_profile_id_embedding_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_generations")),
        sa.UniqueConstraint(
            "profile_id", "generation", name=op.f("uq_index_generations_profile_id")
        ),
    )
    op.create_table(
        "retrieval_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("query_hash", sa.String(length=71), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("degraded", sa.String(length=128), nullable=True),
        sa.Column("selected_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["embedding_profiles.id"],
            name=op.f("fk_retrieval_batches_profile_id_embedding_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_retrieval_batches_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_retrieval_batches_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_retrieval_batches_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_batches")),
        sa.UniqueConstraint("run_id", "purpose", name=op.f("uq_retrieval_batches_run_id")),
    )
    op.create_table(
        "retrieval_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("skill_version_id", sa.Uuid(), nullable=True),
        sa.Column("memory_version_id", sa.Uuid(), nullable=True),
        sa.Column("archive_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("source_hash", sa.String(length=71), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(CASE WHEN skill_version_id IS NULL THEN 0 ELSE 1 END + "
            "CASE WHEN memory_version_id IS NULL THEN 0 ELSE 1 END + "
            "CASE WHEN archive_id IS NULL THEN 0 ELSE 1 END) = 1",
            name=op.f("ck_retrieval_documents_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["session_archives.id"],
            name=op.f("fk_retrieval_documents_archive_id_session_archives"),
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["memory_versions.id"],
            name=op.f("fk_retrieval_documents_memory_version_id_memory_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_retrieval_documents_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["skill_version_id"],
            ["skill_versions.id"],
            name=op.f("fk_retrieval_documents_skill_version_id_skill_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_retrieval_documents_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_documents")),
        sa.UniqueConstraint("source_key", name=op.f("uq_retrieval_documents_source_key")),
    )
    op.create_table(
        "document_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("vector", PGVector().with_variant(sa.JSON(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["retrieval_documents.id"],
            name=op.f("fk_document_embeddings_document_id_retrieval_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["embedding_profiles.id"],
            name=op.f("fk_document_embeddings_profile_id_embedding_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_embeddings")),
        sa.UniqueConstraint(
            "document_id",
            "profile_id",
            "generation",
            "input_hash",
            name=op.f("uq_document_embeddings_document_id"),
        ),
    )
    op.create_table(
        "retrieval_selections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("source_hash", sa.String(length=71), nullable=False),
        sa.Column("text_hash", sa.String(length=71), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("omission_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["retrieval_batches.id"],
            name=op.f("fk_retrieval_selections_batch_id_retrieval_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_selections")),
        sa.UniqueConstraint(
            "batch_id", "source_key", name=op.f("uq_retrieval_selections_batch_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("maintenance_jobs", "next_attempt_at")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retrieval_selections")
    op.drop_table("document_embeddings")
    op.drop_table("retrieval_documents")
    op.drop_table("retrieval_batches")
    op.drop_table("index_generations")
    op.drop_table("embedding_profiles")
    # ### end Alembic commands ###
