"""context_and_memory_foundations

Revision ID: 20260919_0006
Revises: 20260919_0005
Create Date: 2026-09-19 21:45:48.967662
"""

import hashlib
from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import UUID

import sqlalchemy as sa
from alembic import op

revision: str = "20260919_0006"
down_revision: str | Sequence[str] | None = "20260919_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_epoch", sa.Integer(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_jobs")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_maintenance_jobs_dedupe_key")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "memory_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("fact_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope_key = 'workspace' AND session_id IS NULL) OR "
            "(scope_key <> 'workspace' AND session_id IS NOT NULL)",
            name=op.f("ck_memory_entries_memory_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["id", "current_version_id"],
            ["memory_versions.entry_id", "memory_versions.id"],
            name="fk_memory_current_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_memory_entries_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_memory_entries_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_entries")),
        sa.UniqueConstraint(
            "workspace_id", "scope_key", "fact_key", name=op.f("uq_memory_entries_workspace_id")
        ),
    )
    op.create_table(
        "session_archives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("start_sequence", sa.Integer(), nullable=False),
        sa.Column("end_sequence", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(length=71), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_archives_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_archives")),
        sa.UniqueConstraint(
            "session_id",
            "start_sequence",
            "end_sequence",
            "source_hash",
            name=op.f("uq_session_archives_session_id"),
        ),
    )
    op.create_table(
        "memory_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_method", sa.String(length=128), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_version_id", sa.Uuid(), nullable=True),
        sa.Column("origin_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_memory_versions_memory_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["memory_entries.id"],
            name=op.f("fk_memory_versions_entry_id_memory_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["memory_versions.id"],
            name=op.f("fk_memory_versions_supersedes_version_id_memory_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_versions")),
        sa.UniqueConstraint("entry_id", "id", name="uq_memory_entry_version"),
        sa.UniqueConstraint("entry_id", "revision", name="uq_memory_revision"),
    )
    op.create_table(
        "memory_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["memory_entries.id"],
            name=op.f("fk_memory_events_entry_id_memory_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["memory_versions.id"],
            name=op.f("fk_memory_events_version_id_memory_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_events")),
    )
    op.create_table(
        "run_memory_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_run_memory_references_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["memory_versions.id"],
            name=op.f("fk_run_memory_references_version_id_memory_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_memory_references")),
        sa.UniqueConstraint("run_id", "version_id", name=op.f("uq_run_memory_references_run_id")),
    )
    op.create_table(
        "context_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=71), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("policy_hash", sa.String(length=71), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("estimate", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_context_revisions_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["context_revisions.id"],
            name=op.f("fk_context_revisions_parent_id_context_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_context_revisions_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_revisions")),
        sa.UniqueConstraint("run_id", "dedupe_key", name="uq_context_revision_dedupe"),
        sa.UniqueConstraint("run_id", "revision", name="uq_context_revision_number"),
    )
    op.create_table(
        "memory_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("source_hash", sa.String(length=71), nullable=False),
        sa.Column("locator", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_memory_sources_message_id_messages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["memory_versions.id"],
            name=op.f("fk_memory_sources_version_id_memory_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_sources")),
        sa.UniqueConstraint("version_id", "message_id", name=op.f("uq_memory_sources_version_id")),
    )
    op.add_column("messages", sa.Column("task_id", sa.Uuid(), nullable=True))
    op.add_column("messages", sa.Column("run_id", sa.Uuid(), nullable=True))
    op.add_column("messages", sa.Column("session_sequence", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("kind", sa.String(length=32), nullable=True))
    op.add_column("messages", sa.Column("content_hash", sa.String(length=71), nullable=True))
    op.add_column(
        "messages", sa.Column("backfill", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("sessions", sa.Column("workspace_id", sa.Uuid(), nullable=True))
    op.add_column(
        "sessions",
        sa.Column("next_message_sequence", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "tasks",
        sa.Column("history_before_sequence", sa.Integer(), server_default="0", nullable=False),
    )
    bind = op.get_bind()
    metadata = sa.MetaData()
    workspaces = sa.Table("workspaces", metadata, autoload_with=bind)
    sessions = sa.Table("sessions", metadata, autoload_with=bind)
    messages = sa.Table("messages", metadata, autoload_with=bind)
    workspace_id = UUID("00000000-0000-0000-0000-000000000001")
    if bind.dialect.name == "sqlite":
        workspace_id = workspace_id.hex
    bind.execute(
        workspaces.insert().values(
            id=workspace_id, name="Local workspace", created_at=datetime.now(UTC)
        )
    )
    bind.execute(sessions.update().values(workspace_id=workspace_id))
    counts = {}
    for row in bind.execute(
        sa.select(messages).order_by(messages.c.created_at, messages.c.id)
    ).mappings():
        sequence = counts.get(row["session_id"], 0) + 1
        counts[row["session_id"]] = sequence
        digest = "sha256:" + hashlib.sha256(row["content"].encode("utf-8")).hexdigest()
        bind.execute(
            messages.update()
            .where(messages.c.id == row["id"])
            .values(session_sequence=sequence, kind="legacy", content_hash=digest, backfill=True)
        )
    for session_id, count in counts.items():
        bind.execute(
            sessions.update()
            .where(sessions.c.id == session_id)
            .values(next_message_sequence=count + 1)
        )
    with op.batch_alter_table("messages") as batch:
        for name, type_ in [
            ("session_sequence", sa.Integer()),
            ("kind", sa.String(32)),
            ("content_hash", sa.String(71)),
        ]:
            batch.alter_column(name, existing_type=type_, nullable=False)
        batch.create_unique_constraint("uq_messages_run_id", ["run_id", "kind"])
        batch.create_unique_constraint("uq_messages_session_id", ["session_id", "session_sequence"])
        batch.create_foreign_key(
            "fk_messages_run_id_runs", "runs", ["run_id"], ["id"], ondelete="RESTRICT"
        )
        batch.create_foreign_key(
            "fk_messages_task_id_tasks", "tasks", ["task_id"], ["id"], ondelete="RESTRICT"
        )
    with op.batch_alter_table("sessions") as batch:
        batch.alter_column("workspace_id", existing_type=sa.Uuid(), nullable=False)
        batch.create_foreign_key(
            "fk_sessions_workspace_id_workspaces",
            "workspaces",
            ["workspace_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    if bind.dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_memory_current_version",
            "memory_entries",
            "memory_versions",
            ["id", "current_version_id"],
            ["entry_id", "id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "history_before_sequence")
    op.drop_table("memory_sources")
    op.drop_table("context_revisions")
    op.drop_table("run_memory_references")
    op.drop_table("memory_events")
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_memory_current_version", "memory_entries", type_="foreignkey")
    op.drop_table("memory_versions")
    op.drop_table("session_archives")
    op.drop_table("memory_entries")
    with op.batch_alter_table("sessions") as batch:
        batch.drop_constraint("fk_sessions_workspace_id_workspaces", type_="foreignkey")
        batch.drop_column("next_message_sequence")
        batch.drop_column("workspace_id")
    with op.batch_alter_table("messages") as batch:
        batch.drop_constraint("fk_messages_task_id_tasks", type_="foreignkey")
        batch.drop_constraint("fk_messages_run_id_runs", type_="foreignkey")
        batch.drop_constraint("uq_messages_session_id", type_="unique")
        batch.drop_constraint("uq_messages_run_id", type_="unique")
        for name in ("backfill", "content_hash", "kind", "session_sequence", "run_id", "task_id"):
            batch.drop_column(name)
    op.drop_table("workspaces")
    op.drop_table("maintenance_jobs")
    # ### end Alembic commands ###
