"""mcp_discovery_catalogs

Revision ID: 20260920_0008
Revises: 20260920_0007
Create Date: 2026-09-20 19:48:25.963787
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260920_0008"
down_revision: str | Sequence[str] | None = "20260920_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_servers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("latest_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_servers")),
    )
    op.create_table(
        "mcp_catalogs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("server_info", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mcp_servers.id"],
            name=op.f("fk_mcp_catalogs_server_id_mcp_servers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_catalogs")),
        sa.UniqueConstraint("server_id", "revision", name=op.f("uq_mcp_catalogs_server_id")),
    )
    op.create_table(
        "mcp_health",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.String(length=128), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mcp_servers.id"],
            name=op.f("fk_mcp_health_server_id_mcp_servers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_health")),
        sa.UniqueConstraint("server_id", "instance_id", name=op.f("uq_mcp_health_server_id")),
    )
    op.create_table(
        "mcp_tool_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("risk", sa.String(length=8), nullable=False),
        sa.Column("effect", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["mcp_catalogs.id"],
            name=op.f("fk_mcp_tool_reviews_catalog_id_mcp_catalogs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_tool_reviews")),
        sa.UniqueConstraint(
            "catalog_id", "tool_name", "lock_version", name=op.f("uq_mcp_tool_reviews_catalog_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mcp_tool_reviews")
    op.drop_table("mcp_health")
    op.drop_table("mcp_catalogs")
    op.drop_table("mcp_servers")
    # ### end Alembic commands ###
